name: GitHub Actions Publish package
on:
  pull_request:
    branches:
      - main
    types:
      - closed
jobs:
  publish-package:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        persist-credentials: false

    - uses: actions/setup-node/@v3
      with:
        node-version: '16.x'
        registry-url: 'https://registry.npmjs.org'

    - name: Config git
      run: |
        git config --local user.email "cxd2534118085@163.com"
        git config --local user.name "drdevelop"

    - name: install pnpm
      uses: pnpm/action-setup@v2
      with:
          version: 7

    - name: install dependencies
      run: pnpm install

    - name: Release
      run: pnpm run release
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}
        GH_TOKEN: ${{ secrets.ACCESS_TOKEN }}

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.ACCESS_TOKEN }}
