name: GitHub Actions Build and Deploy Demo
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy-docs:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        persist-credentials: false

    - name: install pnpm
      uses: pnpm/action-setup@v2
      with:
          version: 7

    - name: install dependencies
      run: pnpm install

    - name: Build
      run: pnpm run build

    - name: Build docs
      run: pnpm run docs:build

    - name: Publish
      run: pnpm run pub
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}

    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BRANCH: gh-pages
        FOLDER: docs-dist
